/**
 * @fp-pcb/proto -- generated protobuf-es types for the KiCad IPC API.
 *
 * Everything under src/gen is generated by `bun run gen` from the KiCad checkout pinned in
 * KICAD_COMMIT. Messages are exported flat (e.g. `PingSchema`, `ApiRequestSchema`), per module as a
 * namespace (`board_types.Group`), and as descriptors in `kiapiFiles`; `kiapiRegistry` resolves any
 * `type.googleapis.com/kiapi.*` URL for google.protobuf.Any.
 *
 * int64 fields (`Distance.value_nm`, `Vector2.x_nm`, ...) are `bigint` on these wire types.
 */
export * from "./gen/index.js";
export * from "./any.js";
export type { Any, Empty, FieldMask } from "@bufbuild/protobuf/wkt";
export { AnySchema, EmptySchema, FieldMaskSchema } from "@bufbuild/protobuf/wkt";
